services:
  - postgresql
before_script:
  - psql -c 'create database ex_admin_test;' -U postgres
  - nohup phantomjs --wd &
language: elixir
elixir:
  - 1.4
  - 1.3
otp_release:
  - 19
  - 18
sudo: false
script: mix test --include integration:true
notification:
  recipients:
    - smpallen99@yahoo.com
